{
    "name": "Business Project Management",
    "version": "1.0",
    "category": "Project",
    "summary": "Business project workflow management",
    "depends": [
        "base",
        "mail",
        "hr",
        "crm",
        "calendar",
        "sale_management",
        "sale_project",
        "account",
        "project",
    ],
    "data": [

        "security/record_rules.xml",
        "security/user_groups.xml",
        "security/ir.model.access.csv",
        # "data/project_task_type_data.xml",
        "data/approval_sequence.xml",
        "data/sequence_data.xml",
        "data/stage_data.xml",
        "data/mail_template.xml",
        "wizard/report_wizard.xml",
        "report/report_view.xml",
        "report/business_report.xml",
        "views/crm_tag_views.xml",
        "views/reporting.xml",
        "views/business_project_kra_views.xml",
        "views/dashboard_views.xml",
        "views/hr_department_views.xml",
        "views/crm_lead_views.xml",
        "views/project_project_views.xml",
        "views/sale_order_views.xml",
        "views/business_project_approval_views.xml",
        "views/business_project_views.xml",
        "views/business_project_sop_views.xml",
        "views/project_stage_views.xml",
        "views/menu.xml"
    ],
    'assets': {
        'web.assets_backend': [
            'Benjali_management/static/src/js/dashboard.js',
            'Benjali_management/static/src/xml/dashboard.xml',
            'Benjali_management/static/src/scss/dashboard.scss',
        ]},
    "installable": True,
    "application": True,
}
