from . import manpower_requisition
from . import hr_job
from . import hr_applicant
from . import document_type
from . import employee_document
from . import hr_employee
from . import employee_event
from . import attendance_request
from . import attendance_month
from . import hr_leave_type
from . import discipline_case
from . import employee_induction
from . import pms_kra
from . import employee_request
from . import hr_task
from . import process_improvement
