{
    'name': 'HR Operations & Manpower Lifecycle Management',
    'version': '19.0.1.0.0',
    'summary': 'Comprehensive HR software workflow: Manpower, Onboarding, Induction, Attendance, Discipline, PMS, Employee Support, HR Tasks, and Operational Efficiency',
    'category': 'Human Resources',
    'depends': ['hr', 'hr_recruitment', 'mail', 'hr_attendance', 'maintenance', 'hr_holidays'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/sequence.xml',
        'data/exit_document_types.xml',
        'data/document_types.xml',
        'views/discipline_case_views.xml',
        'views/hr_leave_type_views.xml',
        'views/attendance_month_views.xml',
        'views/attendance_request_views.xml',
        'views/employee_events_views.xml',
        'views/employee_induction_views.xml',
        'views/pms_kra_views.xml',
        'views/employee_request_views.xml',
        'views/hr_task_views.xml',
        'views/process_improvement_views.xml',
        'views/hr_employee_views.xml',
        'views/document_type_views.xml',
        'views/hr_job_views.xml',
        'views/hr_applicant_views.xml',
        'views/manpower_requisition_views.xml',
        'wizard/reject_wizard_views.xml',
        'views/menus.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
