{
    'name': 'Manpower Requisition',
    'version': '19.0.1.0.0',
    'summary': 'Department manpower requests with HR review and management approval',
    'category': 'Human Resources/Recruitment',
    'depends': ['hr', 'hr_recruitment', 'mail','hr_attendance','maintenance','hr_holidays'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/cron.xml',
        'data/sequence.xml',
        'data/exit_document_types.xml',
        'data/document_types.xml',
        'views/hr_leave_type_views.xml',
        'views/attendance_month_views.xml',
        'views/attendance_request_views.xml',
        'views/employee_events_views.xml',
        'views/hr_employee_views.xml',
        'views/document_type_views.xml',
        'views/hr_job_views.xml',
        'views/hr_applicant_views.xml',
        'views/manpower_requisition_views.xml',
        'wizard/reject_wizard_views.xml',
        'views/menus.xml',
    ],
    'application': True,
    'installable': True,
    'license': 'LGPL-3',
}
